app/routes.php
<?php
Route::controller('auth', 'AuthController');
Route::controller('sinc', 'SincronizacaoController');

Route::group(array('before' => 'autenticado'), function() {
    Route::get('/', function() {
        return View::make('hello');
    });

    Route::controller('anexo', 'AnexoController');
    Route::controller('configuracao', 'ConfiguracaoController');
    Route::controller('evento', 'EventoController');
    Route::controller('familia', 'FamiliaController');
    Route::controller('genero', 'GeneroController');
    Route::controller('musica', 'MusicaController');
    Route::controller('pedido', 'PedidoController');
    Route::controller('perfil', 'PerfilController');
    Route::controller('produto', 'ProdutoController');
    Route::controller('usuario', 'UsuarioController');
    Route::controller('versao', 'VersaoController');

});

app/models/Produto.php
<?php

/**
 * @property string $catalogo
 * @property string $titulo
 * @property string $artista 
 * @property float $preco 
 * @property string $generos
 * @property string $imagem_destaque 
 * @property string $imagem_listagem 
 * @property string $texto_cheio
 * @property string $texto_reduzido 
 * @property boolean $icms_isento 
 * @property boolean $coletanea 
 * @property boolean $mais_vendido 
 * @property boolean $infantil 
 * @property boolean $lancamento
 * @property dateTime $dt_importacao
 * @property text $texto_cheio
 * @property text $texto_reduzido
 * @property integer $id_status_produto
 * @property integer $id_classe
 * @property dateTime $dt_liberacao
 * @property integer $id_usuario_liberacao
 * @property dateTime $dt_bloqueio
 * @property integer $id_usuario_bloqueio
 * @property varchar $codigo_barras
 */
class Produto extends Modelo {

    protected $table = 'produto';
    protected $primaryKey = 'id_produto';

    const SUBDIR_IMAGENS = 'imagens/';
    const SUBDIR_VIDEO = 'videos/';
    const SUBDIR_AUDIO = 'audio/';
    const ARQ_CAPA = 'capa.jpg';
    const ARQ_THUMB = 'thumb.jpg';

    protected $guarded = array('id_genero');

    public function musicas() {
        return $this->hasMany('Musica', 'id_produto')->orderBy('ordem');
    }

    public function eventos() {
        return $this->hasMany('Evento', 'id_produto')->orderBy('dt_agendada', 'desc');
    }

    public function anexos() {
        return $this->hasMany('Anexo', 'id_produto');
    }

    public function generos() {
        return $this->belongsToMany('Genero', 'produto_genero', 'id_produto', 'id_genero');
    }

    public function classe() {
        return $this->belongsTo('Classe', 'id_classe');
    }

    public function arrayDeGeneros() {
        return $this->generos->lists('id_genero');
    }

    /**
     * Garante que os subdiretórios do produto estão ok e criados
     */
    public function diretoriosOk() {
        $dir = public_path() . Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_IMAGENS;
        $this->diretorioOk($dir);
        $dir = public_path() . Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_VIDEO;
        $this->diretorioOk($dir);
        $dir = public_path() . Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_AUDIO;
        $this->diretorioOk($dir);
    }

    public function caminhoCapa() {
        $dir = public_path() . Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_IMAGENS;
        if (!is_dir($dir)){
            mkdir($dir, 0775, true);
        }
        return $dir . self::ARQ_CAPA;
    }

    public function caminhoThumb() {
        $dir = public_path() . Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_IMAGENS ;
        if (!is_dir($dir)){
            mkdir($dir, 0775, true);
        }
        
        return $dir . self::ARQ_THUMB;
    }

    public function urlCapa() {
        if (File::exists($this->caminhoCapa())) {
            return URL::to(Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_IMAGENS . self::ARQ_CAPA);
        } else {
            return URL::to(Config::get('appvendas.caminho_media') . "/sem_capa.jpg");
        }
    }

    public function urlThumb() {
        if (File::exists($this->caminhoThumb())) {
            return URL::to(Config::get('appvendas.caminho_media') . "/" . $this->id_produto . "/" . self::SUBDIR_IMAGENS . self::ARQ_THUMB);
        } else {
            return URL::to(Config::get('appvendas.caminho_media') . "/sem_thumb.jpg");
        }
    }

    public function diretorioOk($dir) {
        if (!File::isDirectory($dir)) {
            \File::makeDirectory($dir, 755, true);
        }
    }

    public function getNovoAttribute() {
        if ($this->attributes['id_status_produto'] == 1) {
            return true;
        } else {
            return false;
        }
    }

    public function getDescricaoClasseAttribute() {
        if (is_object($this->classe)) {
            return $this->classe->descricao;
        } else {
            return '--';
        }
    }

    public function scopeLiberados($query) {
        return $query->where('id_status_produto', '=', 2);
    }

    public function liberar($id_usuario) {
        $this->id_status_produto = 2;
        $this->id_usuario_liberacao = $id_usuario;
        $this->dt_liberacao = date('Y-m-d H:i:s');
        $this->save();
    }

    public function bloquear($id_usuario) {
        $this->id_status_produto = 1;
        $this->id_usuario_bloqueio = $id_usuario;
        $this->dt_bloqueio = date('Y-m-d H:i:s');
        $this->save();
    }

    public function relacionados() {
        $sql = "select f.id_familia, p.prod_cod, p.id_produto, p.titulo, p.artista, p.catalogo, f.nome"
                . " from produto_familia pf "
                . " join produto p on p.id_produto = pf.id_produto"
                . " join familia f on f.id_familia = pf.id_familia"
                . " where pf.id_familia in (select id_familia from produto_familia where id_produto = ".$this->id_produto.") "
                . " ";
        $regs = \DB::select(\DB::raw($sql));
        return $regs;
    }
}

app/controllers/ProdutoController.php
<?php
class ProdutoController extends BaseController
{
    public function getIndex() {
        $titulo = Input::old('titulo');
        $artista = Input::old('artista');
        $id_classe = Input::old('id_classe');
        $prod_cod = Input::old('prod_cod');
        $catalogo = Input::old('catalogo');
        $classes = array('' => '(todos)') + \Classe::orderBy('descricao')->lists('descricao', 'id_classe');
        $produtos = Produto::where('id_status_produto', '=', 2);
        if (trim($titulo) != '') {
            $produtos = $produtos->where('titulo', 'like', "%" . $titulo . "%");
        }
        if (trim($artista) != '') {
            $produtos = $produtos->where('artista', 'like', "%" . $artista . "%");
        }
        if (trim($id_classe) != '') {
            $produtos = $produtos->where('id_classe', '=', $id_classe);
        }
        if (trim($prod_cod) != '') {
            $produtos = $produtos->where('prod_cod', '=', $prod_cod);
        }
        if (trim($catalogo) != '') {
            $produtos = $produtos->where('catalogo', 'like', "%".$catalogo."%");
        }
        $produtos = $produtos->with('classe')->orderBy('titulo')->paginate(20);
        return View::make('produto.index')->with('registros', $produtos)->with('classes', $classes);
    }

    public function postIndex() {
        return Redirect::to('produto')->withInput();
    }

    public function getNovos() {
        $titulo = Input::old('titulo');
        $artista = Input::old('artista');
        $produtos = Produto::where('titulo', 'like', "%" . $titulo . "%")->where('artista', 'like', "%" . $artista . "%")->where('id_status_produto', '=', 1)->orderBy('titulo')->paginate(20);
        return View::make('produto.novos')->with('registros', $produtos);
    }

    public function postNovos() {
        return Redirect::to('produto/novos')->withInput();
    }

    public function getCadastro($id_produto) {
        $produto = \Produto::find($id_produto);
        $classes = array('' => '(não informada)') + \Classe::orderBy('descricao')->lists('descricao', 'id_classe');
        return View::make('produto.cadastro')->with('nome_aba', 'Cadastro')->with('aba_ativa', 'cadastro')->with('classes', $classes)->with('obj', $produto);
    }

    public function postCadastro() {
        $id_produto = Input::get('id_produto');
        $produto = Produto::find($id_produto);
        $produto->fill(Input::all());
        $produto->save();
        $generos = Input::get('id_genero');
        if (!is_array($generos) || count($generos) == 0) {
            $generos = array();
        }
        $produto->generos()->sync($generos);
        Session::flash('flash_msg', 'Produto atualizado com sucesso!');
        return Redirect::to('/produto/cadastro/' . $id_produto);
    }

    public function getMusicas($id_produto) {
        $produto = Produto::find($id_produto);

        return View::make('produto.musicas')->with('nome_aba', 'Músicas')->with('aba_ativa', 'musicas')->with('icon', 'icon-volume-up')->with('obj', $produto);
    }

    public function getVideos($id_produto) {
        $produto = Produto::find($id_produto);

        return View::make('produto.videos')->with('nome_aba', 'Vídeos')->with('aba_ativa', 'videos')->with('icon', 'icon-film')->with('obj', $produto);
    }

    public function getEventos($id_produto, $id_evento = 0) {
        $produto = Produto::find($id_produto);
        if ($id_evento > 0) {
            $evento = Evento::find($id_evento);
        }
        else {
            $evento = new Evento;
        }

        return View::make('produto.eventos')
            ->with('nome_aba', 'Eventos')
            ->with('aba_ativa', 'eventos')
            ->with('icon', 'icon-calendar')
            ->with('obj', $produto)
            ->with('evento', $evento);
    }

    /**
     * Retorna a tela de capas.
     * @param  int $id_produto Chave do produto
     * @return string             view
     */
    public function getCapas($id_produto) {
        $produto = Produto::find($id_produto);

        return View::make('produto.capas')->with('nome_aba', 'Capas')->with('aba_ativa', 'capas')->with('icon', 'icon-picture')->with('obj', $produto);
    }

    public function getShow($id_produto) {
        $produto = Produto::find($id_produto);

        return View::make('produto.show')->with('obj', $produto);
    }

    public function getLiberar($id_produto) {
        $produto = Produto::find($id_produto);
        $produto->liberar(\Auth::user()->id_usuario);
        Session::flash('flash_msg', 'Produto liberado com sucesso!');
        return Redirect::to('/produto/cadastro/' . $id_produto);
    }

    public function getBloquear($id_produto) {
        $produto = Produto::find($id_produto);
        $produto->bloquear(\Auth::user()->id_usuario);
        Session::flash('flash_msg', 'Produto bloqueado com sucesso!');
        return Redirect::to('/produto/cadastro/' . $id_produto);
    }

    public function getFamilia($id_produto) {
        $produto = \Produto::find($id_produto);
        $relacionados = $produto->relacionados();
        return View::make('produto.familia')->with('nome_aba', 'Família')->with('aba_ativa', 'familia')->with('relacionados', $relacionados)->with('obj', $produto);
    }

    public function getCarregaxml() {

        return View::make('produto.carga');
    }

    public function postCarregaxml() {
        try {
            if ($_FILES["arquivoxml"]["error"] == 0) {
                if ($_FILES["arquivoxml"]["size"] > 0) {
                    $caminho = public_path() . DIRECTORY_SEPARATOR . 'importacao';

                    if (!is_dir($caminho)) {
                        mkdir($caminho, 0775, true);
                    }
                    $caminho.= DIRECTORY_SEPARATOR . "importacao.xml";
                    if (file_exists($caminho)) {
                        unlink($caminho);
                    }
                    move_uploaded_file($_FILES["arquivoxml"]['tmp_name'], $caminho);
                     //6
                    $xml = simplexml_load_file($caminho);
                    $lista = $xml->listaProdutos;
                    $qtd = 0;
                    $novos = 0;
                    $atualizados = 0;
                    foreach ($lista->produto as $produtoXML) {
                        $produto = \Produto::where('prod_cod', '=', trim($produtoXML->codigo))->first();
                        if ($produtoXML->codigo != '') {
                            if (!is_object($produto)) {
                                $produto = new \Produto();
                                $produto->prod_cod = $produtoXML->codigo;
                                $produto->dt_importacao = date('Y-m-d H:i:s');
                                $produto->id_status_produto = 1;
                                $novos++;
                            }
                            else {
                                $atualizados++;
                            }
                            $produto->catalogo = $produtoXML->catalogo;
                            $produto->titulo = $produtoXML->titulo;
                            $produto->artista = $produtoXML->artista;
                            $produto->icms_isento = $produtoXML->icms_isento;
                            $produto->mais_vendido = $produtoXML->mais_vendido;
                            $produto->coletanea = $produtoXML->coletanea;
                            $produto->infantil = $produtoXML->infantil;
                            $produto->lancamento = $produtoXML->lancamento;
                            $produto->codigo_barras = $produtoXML->codigo_barras;
                            $produto->preco = $produtoXML->preco;
                            $produto->save();
                            $qtd++;
                        }
                    }
                    Session::flash('flash_msg', 'Arquivo importado com sucesso!<br/>' . number_format($novos, 0, ",", ".") . " produtos adicionados e " . number_format($atualizados, 0, ",", ".") . " produtos alterados.");
                    return Redirect::to('/produto/carregaxml/');
                }
                else {
                    Session::flash('flash_error', 'Arquivo não informado');
                    return Redirect::to('/produto/carregaxml/');
                }
            }
            else {
                Session::flash('flash_error', 'Erro no recebimento do arquivo:' . $_FILES["arquivoxml"]["error"]);
                return Redirect::to('/produto/carregaxml/');
            }
        }
        catch(Exception $ex) {
            Session::flash('flash_error', 'Ocorreu um problema:' . $ex->getMessage());
            return Redirect::to('/produto/carregaxml/');
        }
    }
}

app/views/produto/cadastro.blade.php
@extends('produto/show')

@section('aba')
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-title">
                    <h3><i class="icon-edit"></i> Descrição do produto</h3>
                </div>
                <div class="box-content">
                    {{ Form::open(array( "class"=>"form-horizontal")) }}
                    {{ Form::hidden('id_produto', $obj->id_produto, array('id' => 'id_produto')) }}
                    @include('html/campo-texto', array('id' => 'catalogo', 'label' => 'Catálogo', 'valor' => $obj->catalogo, 'help' => '', 'opcoes' => array('disabled')))
                    @include('html/campo-texto', array('id' => 'prod_cod', 'label' => 'Código', 'valor' => $obj->prod_cod, 'help' => '', 'opcoes' => array('disabled')))
                    @include('html/campo-texto', array('id' => 'titulo', 'label' => 'Título', 'valor' => $obj->titulo, 'help' => '', 'opcoes' => array('disabled')))
                    @include('html/campo-texto', array('id' => 'artista', 'label' => 'Artista', 'valor' => $obj->artista, 'help' => '', 'opcoes' => array('disabled')))
                    @include('html/campo-texto', array('id' => 'preco', 'label' => 'Preço', 'valor' => 'R$ '.number_format($obj->preco, 2, ",", "."), 'help' => '', 'opcoes' => array('disabled')))
                    @include('html/campo-texto', array('id' => 'codigo_barras', 'label' => 'Código de barras', 'valor' => $obj->codigo_barras, 'help' => ''))
                    @include('html/campo-select', array('id' => 'id_classe', 'label' => 'Classe', 'valores' => $classes, 'valor' => $obj->id_classe,  'help' => '',  array()))
                    @include('html/campo-textarea', array('id' => 'texto_cheio', 'label' => 'Descrição', 'valor' => $obj->texto_cheio, 'help' => ''))
                    @include('html/campo-textarea', array('id' => 'texto_reduzido', 'label' => 'Descrição (red.)', 'valor' => $obj->texto_reduzido, 'help' => ''))
                   <div class="form-group">
                      {{Form::label('lancamento','Lançamento?' , array('id' => 'lancamento', 'class' => 'col-sm-3 col-lg-2 control-label')) }}
                       <div class="col-sm-9 col-lg-10 controls">
                           {{Form::hidden('lancamento', 0)}}
                           <label class="radio-inline">
                              {{ Form::radio('lancamento', 1, (Input::old('lancamento', $obj->lancamento) ? true : false) ) }} Sim
                           </label>
                           <label class="radio-inline">
                              {{ Form::radio('lancamento', 0, (Input::old('lancamento', $obj->lancamento) ? false: true)) }} Não
                           </label>
                       </div>
                    </div>
                    <div class="form-group">
                      {{Form::label('icms_isento','Isento ICMS?' , array('class' => 'col-sm-3 col-lg-2 control-label')) }}
                       <div class="col-sm-9 col-lg-10 controls">
                           {{Form::hidden('icms_isento', 0)}}
                           <label class="radio-inline">
                              {{ Form::radio('icms_isento',  1, (Input::old('icms_isento', $obj->icms_isento) ? true : false)) }} Sim
                           </label>
                           <label class="radio-inline">
                              {{ Form::radio('icms_isento',  0, (Input::old('icms_isento', $obj->icms_isento) ? false : true)) }} Não
                           </label>
                       </div>
                    </div>
                    <div class="form-group">
                        {{Form::label('id_genero', 'Gêneros', array('class' => 'col-sm-3 col-lg-2 control-label')) }}
                        <div class="col-sm-9 col-lg-10 controls">
                            <div class="row">
                                @foreach(Genero::orderBy('nome')->get() as $genero)
                                <div class="col-md-3">
                                    <input type="checkbox" name="id_genero[]" value="{{$genero->id_genero}}"
                                           @if (in_array($genero->id_genero, $obj->arrayDeGeneros() ) )
                                           checked="checked"
                                           @endif
                                           /> {{$genero->nome}}
                                </div>
                                @endforeach
                            </div>

                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Salvar</button>
                        </div>
                    </div>
                    {{Form::close()}}
                </div>
            </div>
        </div>
    </div>

@stop

app/views/produto/familia.blade.php
@extends('produto/show')

@section('aba')
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-title">
                    <h3><i class="icon-list"></i> Produtos associados</h3>
                </div>
                <div class="box-content">
                    @if(count($obj->relacionados()) > 0)
                    <table class="table table-striped table-hover fill-head">
                        <thead>
                            <tr>
                                <th style="width: 40px">#</th>
                                <th style="width: 100px">Família</th>
                                <th style="width: 100px">Código</th>
                                <th style="width: 100px">Catálogo</th>
                                <th style="width: auto">Título</th>
                                <th style="width: auto">Artista</th>
                            </tr>
                        </thead>
                        <tbody>
                            <? $i = 0; ?>
                            @foreach($obj->relacionados() as $produto)
                            <? $i++; ?>
                            <tr>
                                <td>{{ $i }}</td>
                                <td><a href="/familia/edite/{{$produto->id_familia}}">{{$produto->nome}}</a>
                                    
                                </td>
                                <td>{{ $produto->prod_cod }}</td>
                                <td>{{ $produto->catalogo }}</td>
                                <td>{{ $produto->titulo }}</td>
                                <td>{{ $produto->artista }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @else
                    (nenhum evento encontrado)
                    @endif
                </div>
            </div>
        </div>
    </div>

@stop

app/views/produto/index.blade.php
@extends('base')

@section('content')
@include('html/page-title', array('titulo' => 'Produtos', 'subTitulo' => '', 'icon' => 'icon-music'))

@include('html/mensagens')

<!-- BEGIN Main Content -->
<div class="row">
    <div class="col-md-12">
        {{ Form::open(array("class"=>"form-horizontal")) }}
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i>Filtrar por</h3>
                <div class="box-tool">
                    <button type="submit"><i class="icon-search"></i></button>
                </div>
            </div>
            <div class="box-content">
                <div class="row">
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'titulo', 'label' => 'Título', 'valor' => Input::old('titulo'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'artista', 'label' => 'Artista', 'valor' => Input::old('artista'),  'help' => '',  array()))
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @include('html/campo-select', array('id' => 'id_classe', 'label' => 'Classe', 'valores' => $classes, 'valor' => Input::old('id_classe'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'catalogo', 'label' => 'Catálogo', 'valor' => Input::old('catalogo'),  'help' => '',  array()))
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'prod_cod', 'label' => 'Código', 'valor' => Input::old('prod_cod'),  'help' => '',  array()))
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close()}}
    </div>

</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i>Produtos</h3>
                <div class="box-tool">
                </div>
            </div>
            <div class="box-content">
            @if(isset($registros))
                {{$registros->links()}}
            @endif
                <table class="table table-striped table-hover fill-head">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th style="width: 180px">Ação</th>
                            <th style="width: 80px; text-align: center;">ProdCod</th>
                            <th style="width: 80px; text-align: center;">Cat.</th>
                            <th style="width: auto;">Artista</th>
                            <th style="width: auto;">Título</th>
                            <th style="width: auto; text-align: center;">Lançamento?</th>
                            <th style="width: auto; text-align: center;">Classe</th>
                            <th style="width: auto; text-align: center;">Thumb</th>
                        </tr>
                    </thead>
                    @if(isset($registros))
                    <tbody>
                        <? $i = 0; ?>
                        @foreach($registros as $reg)
                        <? $i++; ?>
                        <tr>
                            <td><? print $i; ?></td>
                            <td>
                                <a class="btn btn-primary" href="{{ URL::to('/produto/cadastro/'.$reg->id_produto) }}" title="Detalhes do produto"><i class="icon-pencil"></i></a>
                                <a class="btn btn-lime" href="{{ URL::to('/produto/musicas/'.$reg->id_produto) }}" title="Músicas"><i class="icon-volume-up"></i></a>
                                <a class="btn btn-warning" href="{{ URL::to('/produto/videos/'.$reg->id_produto) }}" title="Vídeos"><i class="icon-film"></i></a>
                                <a class="btn btn-magenta" href="{{ URL::to('/produto/eventos/'.$reg->id_produto) }}" title="Eventos"><i class="icon-calendar"></i></a>
                            </td>
                            <td style="text-align: center;">{{ $reg->prod_cod }}</td>
                            <td style="text-align: center;">{{ $reg->catalogo }}</td>
                            <td>{{ $reg->artista }}</td>
                            <td>{{ $reg->titulo }}</td>
                            <td style="text-align: center;">@if ($reg->lancamento)
                                <i class="icon-check"></i>
                                @else
                                <i class="icon-check-empty"></i>
                                @endif
                            </td>
                            <td style="text-align: center;">{{ $reg->descricao_classe }}</td>
                            <td style="text-align: center;"><img src="{{ $reg->urlThumb() }}" style="max-width:65px;" /></td>
                        </tr>
                        @endforeach
                    </tbody>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>
@stop


@section('scripts')
<script type="text/javascript">

$(document).ready(function(){
    $('#menuProdutos').addClass('active');
});
</script>
@stop

app/views/produto/show.blade.php
@extends('base')

@section('content')
<!-- BEGIN Page Title -->
<div class="page-title">
    <h1><i class="icon-folder-open"></i>{{$obj->artista}}: "{{$obj->titulo}}" ({{$obj->catalogo}})</h1>
</div>
@if ($obj->novo)
<div class="row">
    <div class="col-md-12">
        <a href="/produto/liberar/{{$obj->id_produto}}" class="btn btn-primary pull-right"><i class="icon-unlock"></i> Liberar</a>
    </div>
</div>
@else 
<div class="row">
    <div class="col-md-12">
        <a href="/produto/bloquear/{{$obj->id_produto}}" class="btn btn-danger pull-right"><i class="icon-lock"></i> Bloquear</a>
    </div>
</div>
@endif
<!-- END Page Title -->

@include('html/mensagens')

<!-- BEGIN Main Content -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                @if (!isset($icon))
                <? $icon = 'icon-folder-open'; ?>
                @endif
                
                <h3><i class="{{$icon}}"></i> {{$nome_aba}}</h3>
                <ul class="nav nav-tabs hidden-xs">
                    <li {{($aba_ativa == 'cadastro') ? print 'class="active"' : ''}}><a href="/produto/cadastro/{{ $obj->id_produto}}" >Cadastro</a></li>
                    <li {{($aba_ativa == 'capas') ? print 'class="active"' : ''}}><a href="/produto/capas/{{ $obj->id_produto}}" >Capas</a></li>
                    <li {{($aba_ativa == 'musicas') ? print 'class="active"' : ''}}><a href="/produto/musicas/{{ $obj->id_produto}}" >Músicas</a></li>
                    <li {{($aba_ativa == 'videos') ? print 'class="active"' : ''}}><a href="/produto/videos/{{ $obj->id_produto}}" >Vídeos</a></li>
                    <li {{($aba_ativa == 'eventos') ? print 'class="active"' : ''}}><a href="/produto/eventos/{{ $obj->id_produto}}" >Eventos</a></li>
                    <li {{($aba_ativa == 'familia') ? print 'class="active"' : ''}}><a href="/produto/familia/{{ $obj->id_produto}}" >Família</a></li>
                </ul>

            </div>

            <div class="box-content">
                @yield('aba')
            </div>
        </div>
    </div>
</div>

</div>




@stop

@section('scripts')
<script type="text/javascript" src="/assets/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
<script src="/assets/dropzone-3.8.3/downloads/dropzone.min.js"></script>
<script type="text/javascript">

$(document).ready(function(){
    $('#menuProdutos').addClass('active');
});
function ChamaRota(form, rota, retorno)
{
var xdata = $(form).serialize();
$(retorno).html('<div style="text-align:center"><i class="icon-spinner icon-spin icon-3x"></i> carregando...</div>');
$.ajax({
    type: 'POST'
    , url: rota
    , data: xdata
    , dataType: 'html'
    , success:
            function(data)
            {
                $(retorno).html(data);
            }
});
}

function ExcluirAnexo(id)
{
$.ajax({
    type: 'GET'
    , url: '/anexo/excluir/' + id
    , dataType: 'html'
    , success:
            function(data)
            {
                AtualizarAnexos();
            }
});

}

function AtualizaTipoAnexo(id, id_tipo_anexo)
{
$.ajax({
    type: 'POST'
    , url: '/anexo/atualizartipo/' + id
    , data: {"id_tipo_anexo": $(id_tipo_anexo).val()}
    , success:
            function(data)
            {
                AtualizarAnexos();
            }
});

}

function AtualizarAnexos()
{
$('#containerAnexos').html('<div style="text-align:center; padding:20px;"><i class="icon-spinner icon-spin icon-4x"></i></div>');

$.ajax({
    type: 'GET'
    , url: '/anexo/doproduto/' + $('#id_produto').val()
    , dataType: 'html'
    , success:
            function(data)
            {
                $('#containerAnexos').html(data);
            }
});

}

$(document).ready(function() {
    Dropzone.options.myAwesomeDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        maxFilesize: 2000, // MB
        complete: function(file, done) {
            AtualizarAnexos();
        },
        init: function(){
            this.on("sucess", function(file, response) { alert(response); });
        }
    };
});


$("#nome_completo").keyup(function(e) {
if (e.keyCode == 13) {
    ChamaRota('#buscaCandidato', '/candidato/foradaos', '#candidatosEncontrados');
    return false;
}
});



</script>

@stop