app/routes.php
<?php
Route::controller('auth', 'AuthController');
Route::controller('sinc', 'SincronizacaoController');

Route::group(array('before' => 'autenticado'), function() {
    Route::get('/', function() {
        return View::make('hello');
    });

    Route::controller('anexo', 'AnexoController');
    Route::controller('configuracao', 'ConfiguracaoController');
    Route::controller('evento', 'EventoController');
    Route::controller('familia', 'FamiliaController');
    Route::controller('genero', 'GeneroController');
    Route::controller('musica', 'MusicaController');
    Route::controller('pedido', 'PedidoController');
    Route::controller('perfil', 'PerfilController');
    Route::controller('produto', 'ProdutoController');
    Route::controller('usuario', 'UsuarioController');
    Route::controller('versao', 'VersaoController');

});

app/models/Pedido.php
<?php

/**
 * @property int $id_pedido 
 * @property int $ClienteID 
 * @property int $UnidadeNegocioID 
 * @property int $CondicaoPagamentoID 
 * @property int $numero 
 * @property int $id_usuario_vendedor 
 * @property datetime $dt_pedido 
 * @property datetime $dt_sincronizacao 
 * @property datetime $dt_envio 
 * @property int $id_signus 
 * @property varchar $status_envio 
 * @property varchar $msg_envio 
 * @property timestamp $created_at 
 * @property timestamp $updated_at 
 */
class Pedido extends Modelo {

    protected $table = 'pedido';
    protected $primaryKey = 'id_pedido';
    protected $guarded = array();

    public function scopePendentes() {
        return $this->where('status_envio', '<>', 1);
    }

    public function itens() {
        return $this->hasMany('ItemPedido', 'id_pedido');
    }

    public function cliente(){
        return $this->belongsTo('Cliente', 'ClienteID');
    }
    
    public function vendedor(){
        return $this->belongsTo('Usuario', 'id_usuario_vendedor');
    }
    
    public function getDtPedidoFmtAttribute($valor) {
        return $this->dtHrModelParaView($this->attributes['dt_pedido']);
    }

    public function getDtSincronizacaoFmtAttribute($valor) {
        return $this->dtHrModelParaView($this->attributes['dt_sincronizacao']);
    }

    public function getDtEnvioFmtAttribute($valor) {
        return $this->dtHrModelParaView($this->attributes['dt_envio']);
    }
     
    public function getStatusEnvioDetalhadoAttribute($valor) {
        return $this->attributes['status_envio'];
    }
     
    public function getQtdItensAttribute($valor) {
        return 0;
    }

    public function scopeDoVendedor($query, $id_usuario_vendedor = ''){
        if($id_usuario_vendedor != ''){
            return $query->where('id_usuario_vendedor', '=', $id_usuario_vendedor);
        } else {
            return $query;
        }
    }

    public function scopeDoCliente($query, $ClienteID = ''){
        if($ClienteID != ''){
            return $query->where('ClienteID', '=', $ClienteID);
        } else {
            return $query;
        }
    }

    public function scopePedidoDesde($query, $dt_pedido = ''){
        if($dt_pedido != ''){
            return $query->where('dt_pedido', '>=', $dt_pedido);
        } else {
            return $query;
        }
    }

    public function scopePedidoAte($query, $dt_pedido = ''){
        if($dt_pedido != ''){
            return $query->where('dt_pedido', '<=', $dt_pedido);
        } else {
            return $query;
        }
    }
}

app/controllers/PedidoController.php
<?php

class PedidoController extends BaseController {

    public function getIndex(){
        $rep = new \Appvendas\Repositorios\RepositorioPedido;
        $pedidos = $rep->pedidosFiltro();
        
        $clientes = \Cliente::orderBy('RazaoSocial')->lists('ClienteID', 'RazaoSocial');
        $vendedores = \Usuario::where('fl_representante', '=', 1)->orderBy('nome')->lists('id_usuario', 'nome');
        
        return View::make('pedido.index')
                        ->with('registros', $pedidos)
                        ->with('clientes', $clientes)
                        ->with('vendedores', $vendedores)
        ;        
    }
    
    public function getClientes() {
        $signus = new \Appvendas\Servicos\Signus();
        $signus->abreConexao();
        $ret = $signus->carregaClientes(6, 15);
    }

    public function getCondpag(){
        $signus = new \Appvendas\Servicos\Signus();
        $signus->abreConexao();
        $ret = $signus->carregaCondicaoPagamento(6, 15);
    }
    
    public function getCriateste(){
        $pedido = new \Pedido;
        $pedido->ClienteID = 64;
        $pedido->id_usuario_vendedor = 33;
        $pedido->dt_pedido = '2015-04-07';
        $pedido->UnidadeNegocioID = Configuracao::UnidadeNegocioID();
        $pedido->CondicaoPagamentoID = 1;
        $pedido->save();
        
        $item = new ItemPedido;
        $item->id_pedido = $pedido->id_pedido;
        $item->id_produto = 41645;
        $item->preco = 10.5;
        $item->perc_desconto = 0.1;
        $item->qtd = 10;
        $item->dt_inclusao = date("Y-m-d H:i:s");
        $item->save();

        $item = new ItemPedido;
        $item->id_pedido = $pedido->id_pedido;
        $item->id_produto = 41746;
        $item->preco = 15.5;
        $item->perc_desconto = 0.1;
        $item->qtd = 20;
        $item->dt_inclusao = date("Y-m-d H:i:s");
        $item->save();
    }

    public function getEnviateste($id_pedido){
        $signus = new \Appvendas\Servicos\Signus;
        $signus->abreConexao();
        $pedido = \Pedido::find($id_pedido);
        $ret = $signus->enviaUmPedido($pedido);
    }
    
    public function getTesteenvio(){
        
        return View::make('pedido.teste_signus')
        ;        
        
    }
}

app/views/pedido/index.blade.php
@extends('base')

@section('content')
@include('html/page-title', array('titulo' => 'Pedidos', 'subTitulo' => '', 'icon' => 'icon-shopping-cart'))

@include('html/mensagens')

<!-- BEGIN Main Content -->
<div class="row">
    <div class="col-md-12">
        {{ Form::open(array("class"=>"form-horizontal")) }}
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i>Filtrar por</h3>
                <div class="box-tool">
                    <button type="submit"><i class="icon-search"></i></button>
                </div>
            </div>
            <div class="box-content">
                <div class="row">
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'titulo', 'label' => 'Título', 'valor' => Input::old('titulo'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-6">
                        @include('html/campo-texto', array('id' => 'artista', 'label' => 'Artista', 'valor' => Input::old('artista'),  'help' => '',  array()))
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        @include('html/campo-select', array('id' => 'ClienteID', 'label' => 'Cliente', 'valores' => $clientes, 'valor' => Input::old('ClienteID'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-6">
                        @include('html/campo-select', array('id' => 'id_usuario_vendedor', 'label' => 'Vendedor', 'valores' => $vendedores, 'valor' => Input::old('id_usuario_vendedor'),  'help' => '',  array()))
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close()}}
    </div>

</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i>Pedidos</h3>
                <div class="box-tool">
                </div>
            </div>
            <div class="box-content">
            @if(isset($registros))
                {{$registros->links()}}
            @endif
                <table class="table table-striped table-hover fill-head">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th style="width: 180px">Ação</th>
                            <th style="width: 200px; text-align: left;">Vendedor</th>
                            <th style="width: auto;">Cliente</th>
                            <th style="width: auto; text-align: center;">Data</th>
                            <th style="width: auto; text-align: center;">Itens</th>
                            <th style="width: auto; text-align: center;">Enviado</th>
                        </tr>
                    </thead>
                    @if(isset($registros))
                    <tbody>
                        <? $i = 0; ?>
                        @foreach($registros as $reg)
                        <? $i++; ?>
                        <tr>
                            <td><? print $i; ?></td>
                            <td>
                                <a class="btn btn-primary" href="{{ URL::to('/pedido/edit/'.$reg->id_pedido) }}" title="Detalhes do pedido"><i class="icon-pencil"></i></a>
                            </td>
                            <td style="text-align: center;">{{ $reg->vendedor->fantasia }}</td>
                            <td>{{ $reg->cliente->razao_social }}</td>
                            <td>{{ $reg->dt_pedido_fmt }}</td>
                            <td style="text-align: center;">{{ $reg->qtd_itens}}</td>
                            <td style="text-align: center;">{{ $reg->status_envio_detalhado}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                    @endif
                </table>
            </div>
        </div>
    </div>
</div>
@stop


@section('scripts')
<script type="text/javascript">

$(document).ready(function(){
    $('#menuProdutos').addClass('active');
});
</script>
@stop

app/views/pedido/teste_signus.blade.php
@extends('base')

@section('content')
@include('html/page-title', array('titulo' => 'Pedidos', 'subTitulo' => '', 'icon' => 'icon-shopping-cart'))

@include('html/mensagens')

<!-- BEGIN Main Content -->
<div class="row">
    <div class="col-md-12">
        {{ Form::open(array("class"=>"form-horizontal")) }}
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-table"></i>Teste envio</h3>
                <div class="box-tool">
                    <button type="submit"><i class="icon-search"></i></button>
                </div>
            </div>
            <div class="box-content">
                <div class="row">
                    <div class="col-md-12">
                        @include('html/campo-texto', array('id' => 'url', 'label' => 'Url', 'valor' => 'http://189.44.180.59/SIGNUSERPIntegracaoCMSM2/WSIntegracaoCMS.svc',  'help' => '',  array()))
                    </div>
                    <div class="col-md-12">
                        @include('html/campo-texto', array('id' => 'metodo', 'label' => 'Metodo', 'valor' => Input::old('metodo'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-12">
                        @include('html/campo-texto', array('id' => 'parametros', 'label' => 'Parametros', 'valor' => Input::old('metodo'),  'help' => '',  array()))
                    </div>
                    <div class="col-md-12">
                        @include('html/campo-textarea', array('id' => 'resultado', 'label' => 'Resultado', 'valor' => Input::old('resultado'),  'help' => '',  array()))
                    </div>
                </div>
                <div class="row">
                    <button type='button' class='btn' onclick='envia();'>Testar</button>
                </div>
                
            </div>
        </div>
        {{ Form::close()}}
    </div>
</div>
@stop
@section('scripts')
<script type="text/javascript">

function envia(){
    var metodo = $('#metodo');
    var dados = '<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://tempuri.org/">  <SOAP-ENV:Body>    <ns1:ObterClientes>      <ns1:strXML><![CDATA[<?xml version="1.0"?><Solicitacao><VendedorID>6</VendedorID><UnidadeNegocioID>15</UnidadeNegocioID></Solicitacao>]]></ns1:strXML></ns1:ObterClientes></SOAP-ENV:Body></SOAP-ENV:Envelope>';
    $.ajax({
        url: 'http://189.44.180.59/SIGNUSERPIntegracaoCMSM2/WSIntegracaoCMS.svc?wsdl',
        type: "POST",
        contentType: "application/json; charset=utf-8",
        data: dados,
        dataType: 'json',
        success: function (data, textStatus, jqXHR) {
          alert(textStatus);
          $('#resultado').html(data);
        },
        error: function (jqXHR, textStatus, errorThrown) {
          alert(textStatus);
          console.log(errorThrown);
          console.log(textStatus);
          $('#resultado').html(data);
        },
    });
}
</script>
@stop