app/routes.php
<?php
Route::controller('auth', 'AuthController');
Route::controller('sinc', 'SincronizacaoController');

Route::group(array('before' => 'autenticado'), function() {
    Route::get('/', function() {
        return View::make('hello');
    });

    Route::controller('anexo', 'AnexoController');
    Route::controller('configuracao', 'ConfiguracaoController');
    Route::controller('evento', 'EventoController');
    Route::controller('familia', 'FamiliaController');
    Route::controller('genero', 'GeneroController');
    Route::controller('musica', 'MusicaController');
    Route::controller('pedido', 'PedidoController');
    Route::controller('perfil', 'PerfilController');
    Route::controller('produto', 'ProdutoController');
    Route::controller('usuario', 'UsuarioController');
    Route::controller('versao', 'VersaoController');

});

app/models/Versao.php
<?php
/**
 * @property int $id_versao 
 * @property smallint $num_major 
 * @property smallint $num_minor 
 * @property smallint $num_patch 
 * @property datetime $dt_disponivel 
 * @property text $observacao 
 * @property tinyint $fl_atual 
 * @property timestamp $created_at 
 * @property timestamp $updated_at 
 */
class Versao extends Modelo{

    protected $table = 'versaoapp';
    protected $primaryKey = 'id_versao';
    protected $guarded = array();

    public function caminho() {
        return app_path()."/android_app/appvendas_".$this->num_major."_".$this->num_minor."_".$this->num_patch.".apk";
    }
    
    public function getNumeroAttribute($valor){
        return substr('00'.$this->num_major, -2).".".substr('00'.$this->num_minor, -2).".".substr('00'.$this->num_patch, -2);
    }
    
    public function getDtDisponivelFmtAttribute($valor){
        return $this->dtHrModelParaView($this->attributes['dt_disponivel']);
    }
    
    public function getNomeAttribute($valor){
        return "appvendas.apk";
    }
    
    public function tamanho() {
        filesize($this->caminho());
    }

}

app/controllers/VersaoController.php
<?php

class VersaoController extends BaseController {
    public function getShow($id_versao = 0){
        if ($id_versao > 0){
            $versao = \Versao::find($id_versao);
        } else {
            $versao = new \Versao;
        }
        $versoes = \Versao::orderBy('fl_atual', 'desc')->orderBy('num_major', 'desc')->orderBy('num_minor', 'desc')->orderBy('num_patch', 'desc')->get();
        return View::make('versao.show')
                        ->with('versao', $versao)
                        ->with('versoes', $versoes)
                ;
    }

    public function postStore($id_versao = 0) {
        if ($id_versao > 0){
            $versao = \Versao::find($id_versao);
            $versao->observacao = Input::get('observacao');
            $versao->num_major = intval(Input::get('num_major'));
            $versao->num_minor = intval(Input::get('num_minor'));
            $versao->num_patch = intval(Input::get('num_patch'));
            $versao->save();
            Session::flash('flash_msg', 'Versão atualizada com sucesso!');
            return Redirect::to('/versao/show');           
        } else {
            if (!empty($_FILES)) {
                \DB::table('versaoapp')->update(array('fl_atual'=> 0));
                $versao = new \Versao();
                $versao->observacao = Input::get('observacao');
                $versao->num_major = intval(Input::get('num_major'));
                $versao->num_minor = intval(Input::get('num_minor'));
                $versao->num_patch = intval(Input::get('num_patch'));
                $versao->dt_disponivel = date('Y-m-d H:i:s');
                $versao->fl_atual = 1;
                $versao->save();
                $this->mover($_FILES["versao"]['tmp_name'], $versao->caminho());
                Session::flash('flash_msg', 'Versão criada com sucesso!');
                return Redirect::to('/versao/show');
            } else {
                Session::flash('flash_error', 'Arquivo não recebido!');
                return Redirect::to('/versao/show');
            }
        }
    }

    public function mover($origem, $destino) {
        if (file_exists($destino)) {
            unlink($destino);
        }
        move_uploaded_file($origem, $destino); //6
    }

    public function getTornaratual($id_versao){
        $versao = Versao::find($id_versao);
        \DB::table('versaoapp')->update(array('fl_atual'=> 0));
        $versao->fl_atual = 1;
        $versao->save();
        Session::flash('flash_msg', 'Versão alterada com sucesso!');
        return Redirect::to('/versao/show');
        
    }
    
    public function getDownload($id_versao){
        $versao = Versao::find($id_versao);
        
        $headers = array(
             'Content-Type: application/vnd.android.package-archive',
           );
        
        return Response::download($versao->caminho(), $versao->nome, $headers);
    }

    public function getAtual(){
        $versao = Versao::where('fl_atual', '=', '1')->first();
        $headers = array("Content-Type" => 'application/vnd.android.package-archive');
        return Response::download($versao->caminho(), $versao->nome, $headers);
    }

    public function capturarFile($arquivo) {
        $path_parts = pathinfo($arquivo["name"]);
        $versao = new \Versao();
        return $versao;
    }

    public function getDel($id_versao){
        $versao = Versao::find($id_versao);
        try {
            unlink($versao->caminho());
        }
        catch (Exception $e){

        }
        $versao->delete();
        return Redirect::to('/versao/show/')->with('flash_msg', 'Versão removida com sucesso');
    }
}

app/views/versao/show.blade.php
@extends('base')

@section('content')
<!-- BEGIN Page Title -->
<div class="page-title">
    <h1><i class="icon-folder-open"></i>Versões do aplicativo Android"</h1>
</div>
<!-- END Page Title -->

@include('html/mensagens')

<!-- BEGIN Main Content -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-folder-open"></i>Adicionar versão</h3>
            </div>

            <div class="box-content">
                {{ Form::open(array("url"=>"/versao/store", "class"=>"form-horizontal", "files"=> true)) }}
                {{Form::hidden('id_versao', 0)}}
                    @include('html/campo-texto', array('id' => 'num_major', 'label' => 'Major', 'valor' => '', 'help' => ''))
                    @include('html/campo-texto', array('id' => 'num_minor', 'label' => 'Minor', 'valor' => '', 'help' => ''))
                    @include('html/campo-texto', array('id' => 'num_patch', 'label' => 'Patch', 'valor' => '', 'help' => ''))
                    @include('html/campo-textarea', array('id' => 'observacao', 'label' => 'Observação', 'valor' => '', 'help' => ''))
                    <div class="form-group">
                        <div class="controls">
                            <label class="col-sm-3 col-lg-2 control-label">Apk</label>
                            <div class="col-sm9 col-lg-10 controls">
                                <div class="fileupload fileupload-new" data-provides="fileupload">
                                    <div class="input-group">
                                        <div class="form-control uneditable-input">
                                            <i class="icon-file fileupload-exists"></i> 
                                            <span class="fileupload-preview"></span>
                                        </div>
                                        <div class="input-group-btn">
                                            <a class="btn bun-default btn-file">
                                                <span class="fileupload-new">Selecione o arquivo</span>
                                                <span class="fileupload-exists">Alterar</span>
                                                <input type="file" name="versao" class="file-input"/>
                                            </a>
                                            <a href="#" class="btn btn-default fileupload-exists" data-dismiss="fileupload">Cancelar</a>
                                        </div>
                                        <button type="submit" class="btn btn-primary"><i class="icon-cloud-upload"></i> Enviar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2">
                                <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Salvar</button>
                            </div>
                        </div>
                    {{Form::close()}}
                    </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-title">
                <h3><i class="icon-folder-open"></i>Adicionar versão</h3>
            </div>

            <div class="box-content">
                @if(is_object($versoes ))
                <table class="table table-striped table-hover fill-head">
                    <thead>
                        <tr>
                            <th style="width: 150px; text-align: center;">Ações</th>
                            <th style="width: auto">Número</th>
                            <th style="width: auto;">Data</th>
                            <th style="width: auto;">Observação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <? $i = 0; ?>
                        @foreach($versoes as $versao)
                        <? $i++; ?>
                        <tr>
                            <td style="text-align: center;">
                                @if ($versao->fl_atual == 1)
                                <a href="#" title="Essa é a versão atual" class="btn btn-default"><i class="icon-exclamation"></i></a>                                
                                @else
                                <a href="{{URL::to('versao/tornaratual/'.$versao->id_versao)}}" title="Tornar essa versão a versão atual" class="btn btn-warning"><i class="icon-exclamation"></i></a>
                                @endif
                                <a href="{{URL::to('versao/download/'.$versao->id_versao)}}" target="_blank" title="Download dessa versao" class="btn btn-primary"><i class="icon-download"></i></a>
                                @include('html.link_exclusao', array('url'=> '/versao/del/'.$versao->id_versao, 'msg_confirmacao' => 'Clique para confirmar a exclusão dessa versão', 'title' => 'Excluir', 'icon'=>'icon-trash'))
                            </td>
                            <td>{{ $versao->numero }}</td>
                            <td>{{ $versao->dt_disponivel_fmt }}</td>
                            <td>{{ nl2br($versao->observacao) }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @else
                (nenhuma versão encontrada)
                @endif
            </div>
        </div>
    </div>
</div>

@stop
@section('scripts')
<script type="text/javascript" src="/assets/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>

<script type="text/javascript">

$(document).ready(function(){
    $('#menuTodasVersoes').addClass('active');
});
</script>

@stop