app/routes.php
<?php
Route::controller('auth', 'AuthController');
Route::controller('sinc', 'SincronizacaoController');

Route::group(array('before' => 'autenticado'), function() {
    Route::get('/', function() {
        return View::make('hello');
    });

    Route::controller('anexo', 'AnexoController');
    Route::controller('configuracao', 'ConfiguracaoController');
    Route::controller('evento', 'EventoController');
    Route::controller('familia', 'FamiliaController');
    Route::controller('genero', 'GeneroController');
    Route::controller('musica', 'MusicaController');
    Route::controller('pedido', 'PedidoController');
    Route::controller('perfil', 'PerfilController');
    Route::controller('produto', 'ProdutoController');
    Route::controller('usuario', 'UsuarioController');
    Route::controller('versao', 'VersaoController');

});

app/models/Versao.php
<?php
/**
 * @property int $id_versao 
 * @property smallint $num_major 
 * @property smallint $num_minor 
 * @property smallint $num_patch 
 * @property datetime $dt_disponivel 
 * @property text $observacao 
 * @property tinyint $fl_atual 
 * @property timestamp $created_at 
 * @property timestamp $updated_at 
 */
class Versao extends Modelo{

    protected $table = 'versaoapp';
    protected $primaryKey = 'id_versao';
    protected $guarded = array();

    public function caminho() {
        return app_path()."/android_app/appvendas_".$this->num_major."_".$this->num_minor."_".$this->num_patch.".apk";
    }
    
    public function getNumeroAttribute($valor){
        return substr('00'.$this->num_major, -2).".".substr('00'.$this->num_minor, -2).".".substr('00'.$this->num_patch, -2);
    }
    
    public function getDtDisponivelFmtAttribute($valor){
        return $this->dtHrModelParaView($this->attributes['dt_disponivel']);
    }
    
    public function getNomeAttribute($valor){
        return "appvendas.apk";
    }
    
    public function tamanho() {
        filesize($this->caminho());
    }

}

app/views/base.blade.php
<!DOCTYPE html>
<html>
    @include('html/head')
    <body class="skin-black">

	@include('navbar')

        <!-- BEGIN Container -->
        <div class="container" id="main-container">
            <!-- BEGIN Sidebar -->
            <div id="sidebar" class="navbar-collapse collapse">
				@include('menu')
                <!-- BEGIN Sidebar Collapse Button -->
                <div id="sidebar-collapse" class="visible-lg">
                    <i class="icon-double-angle-left"></i>
                </div>
                <!-- END Sidebar Collapse Button -->
            </div>
            <!-- END Sidebar -->
            <div id="main-content">
            <!-- BEGIN Content -->
			@yield ('content')
                <a id="btn-scrollup" class="btn btn-circle btn-lg" href="#"><i class="icon-chevron-up"></i></a>
            </div>
            <!-- END Content -->
        </div>
        <!-- END Container -->
		<div id="footer">
			<div class="container">
                    <p>2013 © M2 Software.</p>
			</div>
		</div>

        <!--basic scripts-->
        <script src="/assets/jquery/jquery-2.0.3.min.js"></script>
        <script src="/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/assets/bootstrap-inputmask/bootstrap-inputmask.min.js"></script>
        <script src="/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script src="/assets/nicescroll/jquery.nicescroll.min.js"></script>
        <script src="/assets/jquery-cookie/jquery.cookie.js"></script>        <!--page specific plugin scripts-->
        <script src="/assets/flot/jquery.flot.js"></script>
        <script src="/assets/flot/jquery.flot.resize.js"></script>
        <script src="/assets/flot/jquery.flot.pie.js"></script>
        <script src="/assets/flot/jquery.flot.stack.js"></script>
        <script src="/assets/flot/jquery.flot.crosshair.js"></script>
        <script src="/assets/flot/jquery.flot.tooltip.min.js"></script>
        <script src="/assets/sparkline/jquery.sparkline.min.js"></script>
        <script src="/assets/sparkline/jquery.sparkline.min.js"></script>
        <script src="/js/jquery.noty.packaged.min.js"></script>

        <!--flaty scripts-->
        <script src="/js/flaty.js"></script>
        @yield ('scripts')
    </body>
</html>

app/views/hello.blade.php
@extends('base')

@section('content')
    @include('html/page-title', array('titulo' => 'Gestão de conteúdo do catálogo dos representantes', 'subTitulo' => ''))

    @include('html/mensagens')

    <div class="row">
        <div class="col-md-3">
            <a class="tile tile-light-blue" href="{{URL::to('/produto')}}">
                <div class="img">
                    <i class="icon-music"></i>
                </div>
                <div class="content">
                    <p class="title">Produtos</p>
                </div>
            </a>
        </div>

    </div>

@stop

app/views/menu.blade.php
<!-- BEGIN Navlist -->
<ul class="nav nav-list">
    <!-- BEGIN Search Form -->
    <!--                    <li>
                            <form target="#" method="GET" class="search-form">
                                <span class="search-pan">
                                    <button type="submit">
                                        <i class="icon-search"></i>
                                    </button>
                                    <input type="text" name="search" placeholder="Search ..." autocomplete="off" />
                                </span>
                            </form>
                        </li>-->
    <!-- END Search Form -->
    <li id="menuHome"><a href="{{ URL::to('/') }}"><i class="glyphicon glyphicon-home"></i><span>Home</span></a></li>
    <li id="menuFamilias"><a href="{{ URL::to('familia') }}"><i class="icon-link"></i><span>Famílias</span></a></li>
    <li id="menuGeneros"><a href="{{ URL::to('genero') }}"><i class="icon-tag"></i><span>Gêneros</span></a></li>
    <li id="menuProdutos"><a href="{{ URL::to('produto') }}"><i class="icon-music"></i><span>Produtos</span></a></li>
    <li id="menuProdutosBloqueados"><a href="{{ URL::to('produto/novos') }}"><i class="icon-lock"></i><span>Produtos bloqueados</span></a></li>
    <li id="menuPublicidade"><a href="{{ URL::to('anexo/publicidade') }}"><i class="icon-bullhorn"></i><span>Publicidade</span></a></li>
    <li class="divider">&nbsp;</li>
    <li id="menuPedidos"><a href="{{ URL::to('pedido') }}"><i class="icon-shopping-cart"></i><span>Pedidos</span></a></li>
    <li class="divider">&nbsp;</li>
    <li id="menuVersaoAtual"><a href="{{ URL::to('versao/atual') }}" target="_blank"><i class="icon-android"></i><span>Versão atual do app</span></a></li>
    <li id="menuImportarXML"><a href="{{ URL::to('produto/carregaxml') }}" target="_blank"><i class="icon-upload"></i><span>Importar produtos</span></a></li>
    <li id="menuTodasVersoes"><a href="{{ URL::to('versao/show') }}"><i class="icon-calendar"></i><span>Todas versões</span></a></li>
    <li class="divider">&nbsp;</li>
    <li id="menuCorrigir"><a href="{{ URL::to('anexo/acompanhaajuste') }}"><i class="icon-magic"></i><span>Ajustar imagens</span></a></li>
    <li class="divider">&nbsp;</li>
    <li id="menuTodasVersoes"><a href="{{ URL::to('configuracao/show') }}"><i class="icon-cogs"></i><span>Configurações</span></a></li>
    <li class="divider">&nbsp;</li>
    <li>
        <a href="#" class="dropdown-toggle">
            <i class="icon-key"></i><span>Controle de acesso</span>
            <b class="arrow icon-angle-right"></b>
        </a>

        <!-- BEGIN Submenu -->
        <ul class="submenu">
            <li><a href="{{ URL::to('perfil') }}">Perfis</a></li>
            <li><a href="{{ URL::to('usuario') }}">Usuários</a></li>
        </ul>
        <!-- END Submenu -->
    </li>

</ul>
<!-- END Navlist -->

app/views/navbar.blade.php
        <!-- BEGIN Navbar -->
        <div id="navbar" class="navbar navbar-gray">
            <button type="button" class="navbar-toggle navbar-btn collapsed" data-toggle="collapse" data-target="#sidebar">
                <span class="icon-reorder"></span>
            </button>
            <a class="navbar-brand" href="{{ URL::to('/') }}">
                <small>
                    <i class="icon-check-sign"></i>
                    Som Livre - Suporte à Vendas
                </small>
            </a>

            <!-- BEGIN Navbar Buttons -->
            <ul class="nav flaty-nav pull-right">
                <li class="user-profile">
                    <a data-toggle="dropdown" href="#" class="user-menu dropdown-toggle">
                        <span class="hidden-sm" id="user_info">{{\Auth::user()->nome}}
                        </span>
                        <i class="icon-caret-down"></i>
                    </a>

                    <!-- BEGIN User Dropdown -->
                    <ul class="dropdown-menu dropdown-navbar" id="user_menu">
                        <li>
                            <a href="{{ URL::to('usuario/altereminhasenha/')}}">
                                <i class="icon-key"></i>
                                Alterar senha
                            </a>
                        </li>


                        <li class="divider"></li>

                        <li>
                            <a href="{{ URL::to('auth/logout')}}">
                                <i class="icon-off"></i>
                                Sair
                            </a>
                        </li>
                    </ul>
                    <!-- BEGIN User Dropdown -->
                </li>
                <!-- END Button User -->
            </ul>
            <!-- END Navbar Buttons -->
        </div>
        <!-- END Navbar -->